STRESS_FAMILIES = {
    "dense_swarm": {
        "n_threats": 60,
        "n_defenders": 10,
        "n_assets": 3,
        "n_sensors": 4,
        "decoy_fraction": 0.20,
        "fast_fraction": 0.25,
        "sensor_quality": 1.0,
    },
    "resource_poor": {
        "n_threats": 40,
        "n_defenders": 5,
        "n_assets": 2,
        "n_sensors": 3,
        "decoy_fraction": 0.20,
        "fast_fraction": 0.25,
        "sensor_quality": 1.0,
    },
    "decoy_heavy": {
        "n_threats": 45,
        "n_defenders": 8,
        "n_assets": 2,
        "n_sensors": 3,
        "decoy_fraction": 0.45,
        "fast_fraction": 0.15,
        "sensor_quality": 1.0,
    },
    "fast_heavy": {
        "n_threats": 45,
        "n_defenders": 8,
        "n_assets": 2,
        "n_sensors": 3,
        "decoy_fraction": 0.15,
        "fast_fraction": 0.50,
        "sensor_quality": 1.0,
    },
    "sensor_degraded": {
        "n_threats": 35,
        "n_defenders": 8,
        "n_assets": 2,
        "n_sensors": 2,
        "decoy_fraction": 0.20,
        "fast_fraction": 0.25,
        "sensor_quality": 0.65,
    },
}
